sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t sameerdk12/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sameerdk12/react-test npm test -- --coverage

after_success:
  - docker build -t sameerdk12/multi-client ./client
  - docker build -t sameerdk12/multi-nginx ./nginx
  - docker build -t sameerdk12/multi-server ./server
  - docker build -t sameerdk12/multi-worker ./worker
  # Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sameerdk12/multi-client
  - docker push sameerdk12/multi-nginx
  - docker push sameerdk12/multi-server
  - docker push sameerdk12/multi-worker